### ISSUE TITLE
PercentLength doesn't hold percents sensibly

### ISSUE THREAD

**Issue by facetious** [NativeScript/nativescript-ui-feedback#1096]
### Tell us about the problem
When specifying a percent in a template, the resultant object stores both a percentage value and a '%' symbol, which is really confusing.

### Which platform(s) does your issue occur on?
Both iOS and Android.

### Please provide the following version numbers that your issue occurs with:
The current Playground exhibits this.

### Please tell us how to recreate the issue in as much detail as possible.
Run the Playground attached below. Touch the screen. Notice that the output is:
```width: {"unit":"%","value":0.5}```

It should read `width: {"unit":"%","value":"50"}` since it is not 0.5%. I get the intention here, and obviously I understand that numerically, 0.5 === 50%, but you'll notice the left side of that equality is _unitless_. To include a unit, the value must adhere to the unit.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-ng&id=BM3O42

**Comment by NickIliev** [comment]
@facetious the above is by design and indeed the value is a denotation of the percentage received when going to the [convertToString method](https://github.com/NativeScript/NativeScript/blob/05c2460fc4989dae4d7fa1ee52f6d54e0c3113f5/tns-core-modules/ui/styling/style-properties.ts#L73-L75) in the core modules. 

[Here is the TypeScript defenition](https://github.com/NativeScript/NativeScript/blob/05c2460fc4989dae4d7fa1ee52f6d54e0c3113f5/tns-core-modules/ui/core/view/view.d.ts#L44-L50) that describes the denotation of the  `percent` property.
