### ISSUE TITLE
RadListView crash on change to grid layout without `itemHeight`

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/nativescript-ui-feedback#1097]
### Tell us about the problem
On iOS the RadListView crashes the app without an error when you try to change tо grid layout, but don't provide `itemHeight` and `spanCount`. The same works fine for Android and defaults to `spanCount` 2 and some height.

### Which platform(s) does your issue occur on?
_iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 6.1.0
- **CLI:** playground
- **Cross-platform modules:** 5.3.1
- **Runtime(s):** playground

### Please tell us how to recreate the issue in as much detail as possible.
Sample: https://play.nativescript.org/?template=play-tsc&id=LAiIAA&v=6
1. Start on iOS
2. Tap on `Change Layout` in the ActionBar

Result: The app crashes to iOS home.
Expected: There should be default values similar to Android.

**Comment by VladimirAmiorkov** [comment]
This issue has been handled with version [6.4.2]( https://github.com/NativeScript/nativescript-ui-feedback/blob/master/releases/listview.md#642-2019-july-2)

The crash will not longer happen y design the `ListViewGridLayout` in iOS is designed to work for the same size elements, meaning the first item's height will be used by all following cells of the RadListView. Because of this it is recommended to set the `itemHeight` to avoid scenarios where elements are cutoff due to the first item being smaller than them.

**Comment by MartoYankov** [comment]
Just something to add up. It seems setting the `itemHeight` is not "recommended" as stated in the warning - it's mandatory, because if you don't do it, your project will crash.

**Comment by VladimirAmiorkov** [comment]
The app crash has been resolved in the mentioned 6.4.2 version and the warning message has been added in 7.0.1.
