### ISSUE TITLE
RadDataForm picker and segmentEditor don't update value when valuesProvider label is blank

### ISSUE THREAD

**Issue by pbgc** [NativeScript/nativescript-ui-feedback#1230]
When using picker's or segmentEditor's on a RadForm I need to use a blank default value like this:

testValues1: [
      { key: -1, label: "" },
      { key: 1, label: "Option 1" },
      { key: 2, label: "Option 2" },
      { key: 3, label: "Option 3" },
      { key: 4, label: "Option 4" }
    ],

So the default value on the picker (or segmentEditor) is blank and the user must choose one OR use it to select no value (on non required fields).

This always worked until recently! Can tell after which version stopped working ... but I have a big app with 3.7.0 that works and at least after 5.1.0 it stopped working. 

You can see what I'm saying in this playground!

https://play.nativescript.org/?template=play-js&id=v5VlLD&v=39

You can see that on the segmentEditor with blank default label, selecting the first value does not update the observable ... and in the second segmentEditor without it it does!
This is very annoying and breaks several apps.

Thanks in advance! 

EDIT: changed text so it's more clear that the problems occurs when selecting the first value (with blank label) of the segmentEditors)

**Comment by pbgc** [comment]
@elena-p 

I'm really puzzled with your definition of bug severity ....
So for you ... a bug with padding in autocomplete that causes some visual problem when nativescript is updated is high severity ... but this bug that causes that apps that were fully functioning will start submiting WRONG RESULTS from the form (the user chooses a value in a form and that value is not respected!!!! because what will be submited is the original value) is severity LOW ...

Ok .. like I said .. I'm puzzled and worried about using NS in my future developments. Maybe it's time to return to React Native or take a look at Flutter.

**Comment by tgpetrov** [comment]
Hi @pbgc,

When deciding on the severity of an issue, we take multiple things in consideration like the plugin’s usage, the impact that the issue has, if it has some possible workarounds, etc. 

For example, consider [this issue](https://github.com/NativeScript/nativescript-ui-feedback/issues/1220). It impacts everyone using the Numeric editors, while the issue here impact only some of the users of the Segmented Editor (those that need “empty” selection). The issue that you are hitting also has an easy workaround – as it only happens when editor’s value is empty – you can just change that empty value to “ ” (an interval).

However, as both issues happen when an editor’s value is null or empty – their fix was identical, so both of them are fixed in nativescript-ui-dataform@5.1.1. Available for download from npm now.

**Comment by tgpetrov** [comment]
> However, as both issues happen when an editor’s value is null or empty – their fix was identical, so both of them are fixed in nativescript-ui-dataform@5.1.1. Available for download from npm now.

Did you try 5.1.1?

**Comment by pbgc** [comment]
@tgpetrov 

yes I just did and it's working.
Sorry .. When I wrote that I was commenting your sentence about the workaround to the bug on the previous version.
BTW, thanks for the fix and the update!
