### ISSUE TITLE
[Bug] Chart - unable to setup strokeColor for the PointLabel

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-ui-feedback#160]
There is an issue for setting up the `strokeColor` for the Chart's `PointLabel`. This issue is reproducible for Android only. I am attaching sample project, where this could be reproduced.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/943552/Archive.zip)

**Comment by tgpetrov** [comment]
With the current version of nativescript-ui-chart (7.0.0) this issue is no longer reproducible.
P.S. Now there is also an alternative way to set strokeColor for labels (through CSS) which is explained in the documentation articles for the chart in [NativeScript Core](https://docs.nativescript.org/ui/components/Chart/Series/labels), [NativeScript with Angular](https://docs.nativescript.org/angular/ui/ng-components/ng-Chart/Series/labels), [NativeScript with Vue](https://docs.nativescript.org/vuejs/ns-ui/Chart/Series/labels).
